const commonRules = {
  curly: ['error', 'all'],
  eqeqeq: ['error', 'always'],
  'no-undef': 'error',
  'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
  'no-var': 'error',
  'prefer-const': 'error',
};

module.exports = [
  {
    ignores: ['node_modules/**', 'coverage/**'],
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        GmailApp: 'readonly',
        LockService: 'readonly',
        Logger: 'readonly',
        MailApp: 'readonly',
        PropertiesService: 'readonly',
        ScriptApp: 'readonly',
        SpreadsheetApp: 'readonly',
        Utilities: 'readonly',
        JOBOPS_APPLICATION_STATUSES: 'readonly',
        JOBOPS_CONDITIONAL_COLORS: 'readonly',
        JOBOPS_DEFAULT_CONFIG_ROWS: 'readonly',
        JOBOPS_ERROR_CODES: 'readonly',
        JOBOPS_GMAIL_LABEL_NAMES: 'readonly',
        JOBOPS_HEADER_STYLE: 'readonly',
        JOBOPS_MATCH_TYPES: 'readonly',
        JOBOPS_PARSER_VERSION: 'readonly',
        JOBOPS_PRIORITIES: 'readonly',
        JOBOPS_RECRUITER_NEGATIVE_SIGNALS: 'readonly',
        JOBOPS_REQUIRED_CONFIG_KEYS: 'readonly',
        JOBOPS_SCORING_CONTEXTS: 'readonly',
        JOBOPS_SCRIPT_PROPERTY_KEYS: 'readonly',
        JOBOPS_SHEET_DEFINITIONS: 'readonly',
        JOBOPS_SHEET_HEADERS: 'readonly',
        JOBOPS_SHEET_NAMES: 'readonly',
        JOBOPS_TECHNICAL_ROLE_SIGNALS: 'readonly',
        JOBOPS_TECHNOLOGY_NAMES: 'readonly',
        JOBOPS_TRACKING_QUERY_PARAMETERS: 'readonly',
        JOBOPS_WORK_MODES: 'readonly',
        appendJobOpsJobRecords_: 'readonly',
        appendJobOpsParsingErrorRecords_: 'readonly',
        assertValidJobOpsScriptProperties_: 'readonly',
        buildJobOpsDeduplicationIndex_: 'readonly',
        buildJobOpsDeduplicationKey_: 'readonly',
        buildJobOpsJobId_: 'readonly',
        buildJobOpsJobRecord_: 'readonly',
        buildJobOpsParsingErrorRecord_: 'readonly',
        calculateJobOpsScore_: 'readonly',
        canonicalizeJobOpsUrl_: 'readonly',
        classifyJobOpsRole_: 'readonly',
        createJobOpsRecordFromRow_: 'readonly',
        createJobOpsError_: 'readonly',
        detectJobOpsSource_: 'readonly',
        detectJobOpsWorkMode_: 'readonly',
        extractJobOpsExperience_: 'readonly',
        extractJobOpsForwardedMetadata_: 'readonly',
        extractJobOpsLabeledValue_: 'readonly',
        extractJobOpsSalary_: 'readonly',
        extractJobOpsTechnologies_: 'readonly',
        extractJobOpsUrls_: 'readonly',
        evaluateJobOpsJob_: 'readonly',
        finalizeJobOpsThreadLabels_: 'readonly',
        findJobOpsDuplicateMatch_: 'readonly',
        foldJobOpsText_: 'readonly',
        getJobOpsColumnNumber_: 'readonly',
        getJobOpsPriorityForScore_: 'readonly',
        getJobOpsDateKey_: 'readonly',
        getJobOpsRequiredHeaderIndexes_: 'readonly',
        getJobOpsScriptPropertyErrors_: 'readonly',
        getJobOpsSheetSchemaErrors_: 'readonly',
        isDuplicateJobOpsCandidate_: 'readonly',
        isJobOpsUsableDate_: 'readonly',
        jobOpsHtmlToText_: 'readonly',
        markJobOpsThreadsProcessing_: 'readonly',
        mergeJobOpsDuplicateRecord_: 'readonly',
        normalizeAndValidateJobOpsConfig_: 'readonly',
        normalizeJobOpsMultilineText_: 'readonly',
        normalizeJobOpsSingleLineText_: 'readonly',
        normalizeJobOpsText_: 'readonly',
        openJobOpsSpreadsheet_: 'readonly',
        openConfiguredJobOpsSpreadsheet_: 'readonly',
        parseJobOpsMessage_: 'readonly',
        parseJobOpsCvProfiles_: 'readonly',
        parseJobOpsLooseBoolean_: 'readonly',
        parseJobOpsRoleFamilies_: 'readonly',
        parseJobOpsScoringRules_: 'readonly',
        parseJobOpsSender_: 'readonly',
        parseJobOpsSourceDefinitions_: 'readonly',
        readJobOpsConfig_: 'readonly',
        readJobOpsDeduplicationIndex_: 'readonly',
        readJobOpsGmailCandidates_: 'readonly',
        readJobOpsJobsForRescore_: 'readonly',
        readJobOpsCvProfiles_: 'readonly',
        readJobOpsParsingErrorsForDigest_: 'readonly',
        readJobOpsRoleFamilies_: 'readonly',
        readJobOpsScoringRules_: 'readonly',
        readJobOpsScriptProperties_: 'readonly',
        readJobOpsSourceDefinitions_: 'readonly',
        redactJobOpsValue_: 'readonly',
        registerJobOpsCandidate_: 'readonly',
        runJobOpsConfigurationValidation_: 'readonly',
        runJobOpsStatusEdit_: 'readonly',
        runJobOpsSetup_: 'readonly',
        setupJobOpsSpreadsheet_: 'readonly',
        selectJobOpsDigestSections_: 'readonly',
        splitJobOpsList_: 'readonly',
        buildJobOpsDigest_: 'readonly',
        updateJobOpsDuplicateJobRecords_: 'readonly',
        updateJobOpsJobEvaluationFields_: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      ...commonRules,
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', vars: 'local' }],
    },
  },
  {
    files: ['tests/**/*.js', 'scripts/**/*.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        console: 'readonly',
        module: 'readonly',
        process: 'readonly',
        require: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: commonRules,
  },
];
