const commonRules = {
  curly: ['error', 'all'],
  eqeqeq: ['error', 'always'],
  'no-undef': 'error',
  'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
  'no-var': 'error',
  'prefer-const': 'error',
};

module.exports = [
  {
    ignores: ['node_modules/**', 'coverage/**'],
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        GmailApp: 'readonly',
        PropertiesService: 'readonly',
        SpreadsheetApp: 'readonly',
        JOBOPS_APPLICATION_STATUSES: 'readonly',
        JOBOPS_CONDITIONAL_COLORS: 'readonly',
        JOBOPS_DEFAULT_CONFIG_ROWS: 'readonly',
        JOBOPS_ERROR_CODES: 'readonly',
        JOBOPS_GMAIL_LABEL_NAMES: 'readonly',
        JOBOPS_HEADER_STYLE: 'readonly',
        JOBOPS_MATCH_TYPES: 'readonly',
        JOBOPS_PRIORITIES: 'readonly',
        JOBOPS_REQUIRED_CONFIG_KEYS: 'readonly',
        JOBOPS_SCORING_CONTEXTS: 'readonly',
        JOBOPS_SCRIPT_PROPERTY_KEYS: 'readonly',
        JOBOPS_SHEET_DEFINITIONS: 'readonly',
        JOBOPS_SHEET_HEADERS: 'readonly',
        JOBOPS_SHEET_NAMES: 'readonly',
        JOBOPS_WORK_MODES: 'readonly',
        assertValidJobOpsScriptProperties_: 'readonly',
        createJobOpsError_: 'readonly',
        getJobOpsColumnNumber_: 'readonly',
        getJobOpsScriptPropertyErrors_: 'readonly',
        getJobOpsSheetSchemaErrors_: 'readonly',
        normalizeAndValidateJobOpsConfig_: 'readonly',
        normalizeJobOpsText_: 'readonly',
        openJobOpsSpreadsheet_: 'readonly',
        readJobOpsConfig_: 'readonly',
        readJobOpsScriptProperties_: 'readonly',
        redactJobOpsValue_: 'readonly',
        runJobOpsConfigurationValidation_: 'readonly',
        runJobOpsSetup_: 'readonly',
        setupJobOpsSpreadsheet_: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      ...commonRules,
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', vars: 'local' }],
    },
  },
  {
    files: ['tests/**/*.js', 'scripts/**/*.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        console: 'readonly',
        module: 'readonly',
        process: 'readonly',
        require: 'readonly',
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: commonRules,
  },
];
