const JOBOPS_SHEET_NAMES = Object.freeze({
  JOBS: 'Jobs',
  SCORING_RULES: 'ScoringRules',
  ROLE_FAMILIES: 'RoleFamilies',
  CV_PROFILES: 'CVProfiles',
  SOURCES: 'Sources',
  PARSING_ERRORS: 'ParsingErrors',
  CONFIG: 'Config',
});

const JOBOPS_SHEET_HEADERS = Object.freeze({
  Jobs: Object.freeze([
    'JOB_ID',
    'DISCOVERED_AT',
    'LAST_UPDATED_AT',
    'SOURCE',
    'ALL_SOURCES',
    'SOURCE_JOB_ID',
    'COMPANY',
    'POSITION',
    'LOCATION',
    'WORK_MODE',
    'JOB_URL',
    'ROLE_FAMILY',
    'MATCH_SCORE',
    'PRIORITY',
    'RECOMMENDED_CV',
    'CV_LINK',
    'SALARY',
    'EXPERIENCE_REQUESTED',
    'REQUIRED_TECHNOLOGIES',
    'STRONG_MATCHES',
    'RISK_FLAGS',
    'RECRUITER_NAME',
    'RECRUITER_EMAIL',
    'GMAIL_MESSAGE_ID',
    'GMAIL_THREAD_ID',
    'DEDUPLICATION_KEY',
    'PARSER',
    'PARSER_VERSION',
    'STATUS',
    'APPLIED_DATE',
    'FOLLOW_UP_DATE',
    'NOTES',
  ]),
  ScoringRules: Object.freeze([
    'RULE_ID',
    'PATTERN',
    'MATCH_TYPE',
    'CONTEXT',
    'SCORE',
    'RISK_FLAG',
    'ENABLED',
    'NOTES',
    'GROUP',
  ]),
  RoleFamilies: Object.freeze([
    'ROLE_FAMILY',
    'PATTERNS',
    'PRIORITY_ORDER',
    'RECOMMENDED_CV_PROFILE',
    'MINIMUM_REVIEW_SCORE',
    'ENABLED',
    'NOTES',
    'STRATEGIC_LEVEL',
  ]),
  CVProfiles: Object.freeze([
    'CV_PROFILE',
    'DRIVE_URL',
    'TARGET_ROLE_FAMILIES',
    'ENABLED',
    'NOTES',
  ]),
  Sources: Object.freeze([
    'SOURCE',
    'SENDER_DOMAINS',
    'SUBJECT_PATTERNS',
    'PARSER_NAME',
    'ENABLED',
    'PRIORITY_MODIFIER',
    'NOTES',
  ]),
  ParsingErrors: Object.freeze([
    'TIMESTAMP',
    'GMAIL_MESSAGE_ID',
    'SENDER',
    'SUBJECT',
    'DETECTED_SOURCE',
    'PARSER',
    'ERROR_TYPE',
    'ERROR_MESSAGE',
    'RETRY_COUNT',
    'RESOLVED',
    'NOTES',
  ]),
  Config: Object.freeze(['KEY', 'VALUE', 'DESCRIPTION']),
});

const JOBOPS_APPLICATION_STATUSES = Object.freeze([
  'NEW',
  'REVIEW',
  'READY',
  'APPLIED',
  'FOLLOW_UP',
  'SCREENING',
  'TECHNICAL',
  'REJECTED',
  'GHOSTED',
  'OFFER',
  'SKIPPED',
]);

const JOBOPS_WORK_MODES = Object.freeze(['REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN']);
const JOBOPS_PRIORITIES = Object.freeze(['HIGH', 'REVIEW', 'OPTIONAL', 'LOW']);
const JOBOPS_MATCH_TYPES = Object.freeze(['KEYWORD', 'REGEX', 'PHRASE', 'ALL_KEYWORDS']);
const JOBOPS_SCORING_CONTEXTS = Object.freeze([
  'ANY',
  'TITLE',
  'REQUIRED',
  'PREFERRED',
  'NEGATIVE',
]);
const JOBOPS_STRATEGIC_LEVELS = Object.freeze(['DIRECT', 'BRIDGE', 'SECONDARY', 'UNRELATED']);

const JOBOPS_PARSER_VERSION = '1.1.0';
const JOBOPS_TRACKING_QUERY_PARAMETERS = Object.freeze([
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_content',
  'trk',
  'trackingid',
  'ref',
  'source',
]);
const JOBOPS_TECHNOLOGY_NAMES = Object.freeze([
  'Linux',
  'RHEL',
  'CI/CD',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Terraform',
  'Ansible',
  'Prometheus',
  'Grafana',
  'Python',
  'JavaScript',
  'Node.js',
  'GitHub Actions',
  'Jenkins',
  'GitLab CI',
  'IAM',
  'SQL',
]);
const JOBOPS_TECHNICAL_ROLE_SIGNALS = Object.freeze([
  'devops',
  'platform',
  'site reliability',
  'sre',
  'cloud',
  'release',
  'ci/cd',
  'application support',
  'production support',
  'backend',
  'developer',
  'engineer',
  'ingeniero',
  'desarrollador',
  'iam',
  'devsecops',
]);
const JOBOPS_RECRUITER_NEGATIVE_SIGNALS = Object.freeze([
  'newsletter',
  'course',
  'curso',
  'promotion',
  'promoción',
  'invoice',
  'factura',
  'webinar',
  'digest',
  'sale',
  'descuento',
]);

const JOBOPS_GMAIL_LABEL_NAMES = Object.freeze([
  'Jobs/Processed',
  'Jobs/Failed',
  'Jobs/Recruiters',
  'Jobs/Processing',
]);

const JOBOPS_SCRIPT_PROPERTY_KEYS = Object.freeze({
  SPREADSHEET_ID: 'SPREADSHEET_ID',
  USER_EMAIL: 'USER_EMAIL',
});

const JOBOPS_DEFAULT_CONFIG_ROWS = Object.freeze([
  ['TIMEZONE', 'America/Bogota', 'Zona horaria usada por JobOps.'],
  ['DIGEST_ENABLED', true, 'Habilita el resumen diario.'],
  ['DIGEST_HOUR', 8, 'Hora local del resumen diario, entre 0 y 23.'],
  ['FOLLOW_UP_BUSINESS_DAYS', 5, 'Días hábiles antes del seguimiento.'],
  ['MAX_MESSAGES_PER_RUN', 100, 'Máximo de mensajes procesados por ejecución.'],
  ['MAX_DIGEST_JOBS', 10, 'Máximo de vacantes principales en el resumen.'],
  ['HIGH_PRIORITY_THRESHOLD', 15, 'Puntaje mínimo para prioridad HIGH.'],
  ['REVIEW_THRESHOLD', 10, 'Puntaje mínimo para prioridad REVIEW.'],
  ['OPTIONAL_THRESHOLD', 6, 'Puntaje mínimo para prioridad OPTIONAL.'],
  ['RECRUITER_SCORE_BONUS', 5, 'Bono de puntaje para oportunidades de reclutadores.'],
  ['LOOKBACK_DAYS', 7, 'Días de antigüedad incluidos en la búsqueda de Gmail.'],
  ['DRY_RUN', false, 'Procesa sin modificar Gmail, Sheets ni enviar correo.'],
]);

const JOBOPS_DEFAULT_SCORING_RULE_ROWS = Object.freeze([
  ['SCORE_LINUX', 'Linux', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_RHEL', 'RHEL', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_CICD', 'CI/CD', 'PHRASE', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_DOCKER', 'Docker', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_AWS', 'AWS', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_TERRAFORM', 'Terraform', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_ANSIBLE', 'Ansible', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_PROMETHEUS', 'Prometheus', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_GRAFANA', 'Grafana', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  [
    'SCORE_PRODUCTION_SUPPORT',
    'Production Support',
    'PHRASE',
    'ANY',
    3,
    '',
    true,
    'Regla inicial.',
  ],
  ['SCORE_PYTHON', 'Python', 'KEYWORD', 'ANY', 2, '', true, 'Regla inicial.'],
  ['SCORE_IAM', 'IAM', 'KEYWORD', 'ANY', 2, '', true, 'Regla inicial.'],
  ['RISK_SENIOR', 'Senior', 'KEYWORD', 'NEGATIVE', -5, 'SENIOR_TITLE', true, 'Riesgo inicial.'],
  ['RISK_LEAD', 'Lead', 'KEYWORD', 'NEGATIVE', -5, 'LEAD_TITLE', true, 'Riesgo inicial.'],
  [
    'RISK_PRINCIPAL',
    'Principal',
    'KEYWORD',
    'NEGATIVE',
    -6,
    'PRINCIPAL_TITLE',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_FIVE_YEARS',
    '5+ years',
    'PHRASE',
    'REQUIRED',
    -4,
    'FIVE_PLUS_YEARS',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_SEVEN_YEARS',
    '7+ years',
    'PHRASE',
    'REQUIRED',
    -6,
    'SEVEN_PLUS_YEARS',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_HELP_DESK_L1',
    'Help Desk L1',
    'PHRASE',
    'ANY',
    -4,
    'HELP_DESK_L1',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_SOLE_ON_CALL',
    'sole on-call',
    'PHRASE',
    'REQUIRED',
    -3,
    'SOLE_ON_CALL',
    true,
    'Riesgo inicial.',
  ],
]);

const JOBOPS_DEFAULT_ROLE_FAMILY_ROWS = Object.freeze([
  [
    'DEVOPS_PLATFORM_SRE',
    'devops,platform engineer,site reliability,sre',
    1,
    'DEVOPS_PLATFORM',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'CLOUDOPS_CLOUD_SUPPORT',
    'cloud operations,cloud support,cloud engineer',
    2,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'RELEASE_CICD',
    'release engineer,release management,ci/cd,build engineer',
    3,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'APPLICATION_PRODUCTION_SUPPORT',
    'application support,production support,l2 support,l3 support',
    4,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'BACKEND_WITH_DEVOPS',
    'backend engineer,backend developer,automation engineer',
    5,
    'BACKEND_AUTOMATION',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'BACKEND_PLATFORM_IAM_DEVSECOPS',
    'iam,devsecops,platform security,backend platform',
    6,
    'BACKEND_AUTOMATION',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'OTHER_TECHNICAL',
    'technical,engineer,developer,operations',
    7,
    'CV_TO_CREATE',
    6,
    true,
    'Familia de respaldo técnico.',
  ],
  ['UNRELATED', '', 8, 'CV_TO_CREATE', 999, true, 'Oportunidades no relacionadas.'],
]);

const JOBOPS_DEFAULT_CV_PROFILE_ROWS = Object.freeze([
  ['DEVOPS_PLATFORM', '', 'DEVOPS_PLATFORM_SRE', true, 'Agregar enlace de Drive.'],
  [
    'CLOUDOPS_RELEASE_SUPPORT',
    '',
    'CLOUDOPS_CLOUD_SUPPORT,RELEASE_CICD,APPLICATION_PRODUCTION_SUPPORT',
    true,
    'Agregar enlace de Drive.',
  ],
  [
    'BACKEND_AUTOMATION',
    '',
    'BACKEND_WITH_DEVOPS,BACKEND_PLATFORM_IAM_DEVSECOPS',
    true,
    'Agregar enlace de Drive.',
  ],
  ['CV_TO_CREATE', '', 'OTHER_TECHNICAL,UNRELATED', true, 'No existe un CV específico.'],
]);

// Phase 4 strategy upgrade. The original seed rows above remain as migration
// baselines so setup can safely recognize uncustomized installations.
const JOBOPS_STRATEGY_SCORING_RULE_ROWS = Object.freeze([
  ['SCORE_LINUX', 'Linux', 'KEYWORD', 'ANY', 4, '', true, 'Infraestructura.', ''],
  ['SCORE_RHEL', 'RHEL', 'KEYWORD', 'ANY', 4, '', true, 'Infraestructura.', ''],
  ['SCORE_UBUNTU', 'Ubuntu Server', 'PHRASE', 'ANY', 3, '', true, 'Infraestructura.', ''],
  ['SCORE_CICD', 'CI/CD', 'PHRASE', 'ANY', 4, '', true, 'Entrega continua.', ''],
  ['SCORE_GITHUB_ACTIONS', 'GitHub Actions', 'PHRASE', 'ANY', 4, '', true, 'Entrega continua.', ''],
  ['SCORE_GITLAB_CI', 'GitLab CI', 'PHRASE', 'ANY', 4, '', true, 'Entrega continua.', ''],
  ['SCORE_BASH', 'Bash', 'KEYWORD', 'ANY', 3, '', true, 'AutomatizaciÃ³n.', ''],
  ['SCORE_DOCKER', 'Docker', 'KEYWORD', 'ANY', 4, '', true, 'Contenedores.', ''],
  ['SCORE_DOCKER_COMPOSE', 'Docker Compose', 'PHRASE', 'ANY', 3, '', true, 'Contenedores.', ''],
  ['SCORE_AWS', 'AWS', 'KEYWORD', 'ANY', 3, '', true, 'Cloud.', ''],
  ['SCORE_CLOUDWATCH', 'CloudWatch', 'KEYWORD', 'ANY', 3, '', true, 'Cloud.', ''],
  ['SCORE_TERRAFORM', 'Terraform', 'KEYWORD', 'ANY', 3, '', true, 'AutomatizaciÃ³n.', ''],
  ['SCORE_ANSIBLE', 'Ansible', 'KEYWORD', 'ANY', 3, '', true, 'AutomatizaciÃ³n.', ''],
  [
    'SCORE_PROMETHEUS',
    'Prometheus',
    'KEYWORD',
    'ANY',
    3,
    '',
    true,
    'Observabilidad.',
    'OBSERVABILITY_SIGNAL',
  ],
  [
    'SCORE_GRAFANA',
    'Grafana',
    'KEYWORD',
    'ANY',
    3,
    '',
    true,
    'Observabilidad.',
    'OBSERVABILITY_SIGNAL',
  ],
  ['SCORE_LOKI', 'Loki', 'KEYWORD', 'ANY', 3, '', true, 'Observabilidad.', 'OBSERVABILITY_SIGNAL'],
  [
    'SCORE_OBSERVABILITY',
    'Observability',
    'KEYWORD',
    'ANY',
    3,
    '',
    true,
    'Observabilidad.',
    'OBSERVABILITY_SIGNAL',
  ],
  [
    'SCORE_MONITORING',
    'Monitoring',
    'KEYWORD',
    'ANY',
    3,
    '',
    true,
    'Observabilidad.',
    'OBSERVABILITY_SIGNAL',
  ],
  [
    'SCORE_PRODUCTION_SUPPORT',
    'Production Support',
    'PHRASE',
    'ANY',
    3,
    '',
    true,
    'Soporte tÃ©cnico.',
    'SUPPORT_SPECIALTY',
  ],
  [
    'SCORE_APPLICATION_SUPPORT',
    'Application Support',
    'PHRASE',
    'ANY',
    3,
    '',
    true,
    'Soporte tÃ©cnico.',
    'SUPPORT_SPECIALTY',
  ],
  [
    'SCORE_TROUBLESHOOTING',
    'Troubleshooting',
    'KEYWORD',
    'ANY',
    3,
    '',
    true,
    'OperaciÃ³n tÃ©cnica.',
    '',
  ],
  [
    'SCORE_INCIDENT_MANAGEMENT',
    'Incident Management',
    'PHRASE',
    'ANY',
    2,
    '',
    true,
    'OperaciÃ³n tÃ©cnica.',
    '',
  ],
  ['SCORE_PYTHON', 'Python', 'KEYWORD', 'ANY', 2, '', true, 'Backend y automatizaciÃ³n.', ''],
  ['SCORE_DJANGO', 'Django', 'KEYWORD', 'ANY', 2, '', true, 'Backend y automatizaciÃ³n.', ''],
  ['SCORE_FASTAPI', 'FastAPI', 'KEYWORD', 'ANY', 2, '', true, 'Backend y automatizaciÃ³n.', ''],
  ['SCORE_REST_APIS', 'REST APIs', 'PHRASE', 'ANY', 2, '', true, 'IntegraciÃ³n.', ''],
  ['SCORE_NGINX', 'Nginx', 'KEYWORD', 'ANY', 2, '', true, 'Infraestructura web.', ''],
  ['SCORE_DNS', 'DNS', 'KEYWORD', 'ANY', 2, '', true, 'Infraestructura web.', ''],
  ['SCORE_TLS', 'TLS', 'KEYWORD', 'ANY', 2, '', true, 'Infraestructura web.', ''],
  ['SCORE_IAM', 'IAM', 'KEYWORD', 'ANY', 2, '', true, 'Seguridad de infraestructura.', ''],
  [
    'SCORE_ACCESS_CONTROL',
    'Access Control',
    'PHRASE',
    'ANY',
    2,
    '',
    true,
    'Seguridad de infraestructura.',
    '',
  ],
  [
    'SCORE_LEAST_PRIVILEGE',
    'Least Privilege',
    'PHRASE',
    'ANY',
    2,
    '',
    true,
    'Seguridad de infraestructura.',
    '',
  ],
  ['SCORE_SAST', 'SAST', 'KEYWORD', 'ANY', 2, '', true, 'Seguridad de entrega.', ''],
  ['SCORE_SYSTEMD', 'Systemd', 'KEYWORD', 'ANY', 2, '', true, 'Infraestructura Linux.', ''],
  ['SCORE_SQL', 'SQL', 'KEYWORD', 'ANY', 2, '', true, 'Soporte de aplicaciones.', 'DATABASE'],
  [
    'SCORE_POSTGRES',
    'PostgreSQL',
    'KEYWORD',
    'ANY',
    2,
    '',
    true,
    'Soporte de aplicaciones.',
    'DATABASE',
  ],
  [
    'BONUS_JUNIOR',
    '\\b(?:junior|jr\\.?|associate|analyst|engineer i|level 1|entry level)\\b',
    'REGEX',
    'TITLE',
    4,
    '',
    true,
    'Seniority de entrada.',
    'SENIORITY',
  ],
  [
    'RISK_SENIOR',
    '\\bsenior\\b|\\bsr\\.?(?:\\s|$)',
    'REGEX',
    'TITLE',
    -7,
    'SENIOR_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_LEAD',
    'Lead',
    'KEYWORD',
    'TITLE',
    -8,
    'LEAD_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_STAFF',
    'Staff',
    'KEYWORD',
    'TITLE',
    -9,
    'STAFF_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_PRINCIPAL',
    'Principal',
    'KEYWORD',
    'TITLE',
    -10,
    'PRINCIPAL_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_ARCHITECT',
    'Architect',
    'KEYWORD',
    'TITLE',
    -7,
    'ARCHITECT_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_MANAGER',
    'Manager',
    'KEYWORD',
    'TITLE',
    -8,
    'MANAGER_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_HEAD',
    'Head',
    'KEYWORD',
    'TITLE',
    -10,
    'HEAD_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'RISK_DIRECTOR',
    'Director',
    'KEYWORD',
    'TITLE',
    -10,
    'DIRECTOR_TITLE',
    true,
    'Seniority superior.',
    'SENIORITY',
  ],
  [
    'BONUS_ZERO_TO_TWO_YEARS',
    '\\b(?:0\\s*(?:-|to|a)\\s*2|[012])\\s*\\+?\\s*(?:years?|anos?)\\b',
    'REGEX',
    'REQUIRED',
    3,
    '',
    true,
    'Experiencia requerida accesible.',
    'REQUIRED_EXPERIENCE',
  ],
  [
    'RISK_FOUR_YEARS',
    '\\b4\\s*\\+?\\s*(?:years?|anos?)\\b',
    'REGEX',
    'REQUIRED',
    -2,
    'FOUR_YEARS_REQUIRED',
    true,
    'Experiencia requerida.',
    'REQUIRED_EXPERIENCE',
  ],
  [
    'RISK_FIVE_YEARS',
    '\\b5\\s*\\+?\\s*(?:years?|anos?)\\b',
    'REGEX',
    'REQUIRED',
    -5,
    'FIVE_YEARS_REQUIRED',
    true,
    'Experiencia requerida.',
    'REQUIRED_EXPERIENCE',
  ],
  [
    'RISK_SIX_YEARS',
    '\\b6\\s*\\+?\\s*(?:years?|anos?)\\b',
    'REGEX',
    'REQUIRED',
    -6,
    'SIX_YEARS_REQUIRED',
    true,
    'Experiencia requerida.',
    'REQUIRED_EXPERIENCE',
  ],
  [
    'RISK_SEVEN_YEARS',
    '\\b(?:[7-9]|[1-9][0-9])\\s*\\+?\\s*(?:years?|anos?)\\b',
    'REGEX',
    'REQUIRED',
    -8,
    'SEVEN_PLUS_YEARS_REQUIRED',
    true,
    'Experiencia requerida.',
    'REQUIRED_EXPERIENCE',
  ],
  [
    'RISK_K8S_REQUIRED',
    'Kubernetes',
    'KEYWORD',
    'REQUIRED',
    -1,
    'KUBERNETES_REQUIRED',
    true,
    'Kubernetes requerido.',
    'KUBERNETES_SCOPE',
  ],
  [
    'RISK_K8S_ADVANCED',
    'advanced kubernetes|production',
    'ALL_KEYWORDS',
    'REQUIRED',
    -3,
    'ADVANCED_KUBERNETES',
    true,
    'Kubernetes avanzado en producciÃ³n.',
    'KUBERNETES_SCOPE',
  ],
  [
    'RISK_K8S_OWNERSHIP',
    'kubernetes|ownership|production',
    'ALL_KEYWORDS',
    'REQUIRED',
    -5,
    'KUBERNETES_OWNERSHIP',
    true,
    'Ownership de clÃºster productivo.',
    'KUBERNETES_SCOPE',
  ],
  [
    'RISK_PLATFORM_OWNERSHIP',
    'kubernetes|platform|design',
    'ALL_KEYWORDS',
    'REQUIRED',
    -6,
    'FULL_PLATFORM_OWNERSHIP',
    true,
    'DiseÃ±o de plataforma completa.',
    'KUBERNETES_SCOPE',
  ],
  [
    'RISK_HELP_DESK_L1',
    'Help Desk L1',
    'PHRASE',
    'ANY',
    -8,
    'HELP_DESK_L1',
    true,
    'Soporte de escritorio.',
    'DESKTOP_SUPPORT',
  ],
  [
    'RISK_DESKTOP_SUPPORT',
    'Desktop Support',
    'PHRASE',
    'ANY',
    -8,
    'DESKTOP_SUPPORT',
    true,
    'Soporte de escritorio.',
    'DESKTOP_SUPPORT',
  ],
  [
    'RISK_FIELD_SUPPORT',
    'Field Support',
    'PHRASE',
    'ANY',
    -8,
    'FIELD_SUPPORT',
    true,
    'Soporte en campo.',
    'DESKTOP_SUPPORT',
  ],
  [
    'RISK_HARDWARE_SUPPORT',
    'Hardware Support',
    'PHRASE',
    'ANY',
    -7,
    'HARDWARE_SUPPORT',
    true,
    'Soporte de hardware.',
    'DESKTOP_SUPPORT',
  ],
  [
    'RISK_PRINTER_SUPPORT',
    'Printer',
    'KEYWORD',
    'ANY',
    -10,
    'PRINTER_SUPPORT',
    true,
    'Soporte de impresoras.',
    'DESKTOP_SUPPORT',
  ],
  [
    'RISK_FUNCTIONAL_SUPPORT',
    'functional support',
    'PHRASE',
    'ANY',
    -6,
    'FUNCTIONAL_SUPPORT',
    true,
    'Soporte funcional.',
    '',
  ],
  ['RISK_MANUAL_QA', 'manual qa', 'PHRASE', 'ANY', -5, 'MANUAL_QA_ONLY', true, 'QA manual.', ''],
  [
    'RISK_PROJECT_MANAGEMENT',
    'project management',
    'PHRASE',
    'ANY',
    -7,
    'PROJECT_MANAGEMENT_ONLY',
    true,
    'GestiÃ³n de proyecto.',
    '',
  ],
  [
    'RISK_BUSINESS_ANALYST',
    'business analyst',
    'PHRASE',
    'ANY',
    -6,
    'BUSINESS_ANALYST_ONLY',
    true,
    'AnÃ¡lisis de negocio.',
    '',
  ],
  [
    'RISK_SOLE_ON_CALL',
    'sole on-call',
    'PHRASE',
    'REQUIRED',
    -5,
    'SOLE_ON_CALL',
    true,
    'Cobertura individual.',
    'ON_CALL_SCOPE',
  ],
  [
    'RISK_SOLO_24_7',
    '24/7|solo',
    'ALL_KEYWORDS',
    'REQUIRED',
    -6,
    'SOLO_24_7_COVERAGE',
    true,
    'Cobertura individual 24/7.',
    'ON_CALL_SCOPE',
  ],
  [
    'RISK_MULTICLOUD_ADVANCED',
    'multicloud|architecture',
    'ALL_KEYWORDS',
    'REQUIRED',
    -5,
    'ADVANCED_MULTICLOUD',
    true,
    'Arquitectura multicloud avanzada.',
    '',
  ],
  [
    'SYNERGY_CLOUD_SUPPORT',
    'cloud support|linux|troubleshooting',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Cloud Support + Linux + troubleshooting.',
    '',
  ],
  [
    'SYNERGY_APPLICATION_SUPPORT',
    'application support|api|sql|logs',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Application Support + APIs + SQL + logs.',
    '',
  ],
  [
    'SYNERGY_BACKEND_DEVOPS',
    'backend|docker|ci/cd',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Backend + Docker + CI/CD.',
    '',
  ],
  [
    'SYNERGY_LINUX_AUTOMATION',
    'linux|ansible',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Linux + automatizaciÃ³n.',
    '',
  ],
  [
    'SYNERGY_RELEASE_CICD',
    'release|ci/cd|git',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Release + CI/CD + Git.',
    '',
  ],
  [
    'SYNERGY_OBSERVABILITY',
    'observability|prometheus|grafana',
    'ALL_KEYWORDS',
    'ANY',
    3,
    '',
    true,
    'Observability + Prometheus + Grafana.',
    '',
  ],
  [
    'SYNERGY_IAM',
    'iam|aws|access control',
    'ALL_KEYWORDS',
    'ANY',
    2,
    '',
    true,
    'IAM + cloud + access control.',
    '',
  ],
]);

const JOBOPS_STRATEGY_ROLE_FAMILY_ROWS = Object.freeze([
  [
    'DEVOPS_CLOUDOPS_JR',
    'devops junior,junior devops engineer,devops engineer jr,devops engineer i,devops engineer,devops analyst,devops associate,cloud devops analyst,cloud devops jr,desarrollador devops jr,ingeniero devops junior,analista devops,cloudops engineer,cloud operations engineer,cloud operations analyst,cloud infrastructure engineer jr,infrastructure automation engineer jr',
    1,
    'DEVOPS_PLATFORM',
    8,
    true,
    'Roles directos DevOps/CloudOps de entrada.',
    'DIRECT',
  ],
  [
    'PLATFORM_SRE_ASSOCIATE',
    'platform engineer junior,junior platform engineer,platform engineer i,platform ops engineer,sre associate,junior sre,site reliability engineer i,sre support analyst,cloud site reliability engineer associate,service reliability engineer,reliability engineer associate',
    2,
    'DEVOPS_PLATFORM',
    8,
    true,
    'Roles directos Platform/SRE de entrada.',
    'DIRECT',
  ],
  [
    'CLOUD_SUPPORT_OPERATIONS',
    'cloud support engineer,cloud support analyst,aws cloud support,azure cloud support,gcp cloud support,cloud infrastructure support,cloud systems administrator,cloud operations support,cloud noc,cloud integration,ingeniero soporte cloud,analista operaciones cloud,soporte infraestructura cloud',
    3,
    'CLOUDOPS_SUPPORT',
    9,
    true,
    'Rol puente de operaciones y soporte cloud.',
    'BRIDGE',
  ],
  [
    'APPLICATION_PRODUCTION_SUPPORT',
    'application support engineer,application support analyst,production support engineer,production support analyst,application ops,technical application support,product support engineer,software support l2,software support l3,backend support,customer escalation engineer,application support l2,application support l3,soporte de aplicaciones,soporte produccion,soporte tecnico l2,soporte tecnico l3',
    4,
    'CLOUDOPS_SUPPORT',
    9,
    true,
    'Rol puente de soporte tÃ©cnico de aplicaciones.',
    'BRIDGE',
  ],
  [
    'RELEASE_CICD_AUTOMATION',
    'release engineer,build and release engineer,ci/cd engineer,deployment engineer,release management analyst,devops release engineer,environment management,software configuration engineer,deployment automation,ingeniero de releases,automatizacion de despliegues',
    5,
    'DEVOPS_PLATFORM',
    9,
    true,
    'Rol puente de release, CI/CD y automatizaciÃ³n.',
    'BRIDGE',
  ],
  [
    'LINUX_INFRASTRUCTURE',
    'linux systems engineer,linux system administrator junior,infrastructure engineer jr,infrastructure operations,systems engineer,systems automation,middleware engineer,web infrastructure,cloud systems administrator,ingeniero linux,administrador linux junior,operaciones de infraestructura',
    6,
    'DEVOPS_PLATFORM',
    9,
    true,
    'Rol puente de infraestructura Linux.',
    'BRIDGE',
  ],
  [
    'BACKEND_WITH_DEVOPS',
    'backend engineer,backend developer,python backend,django developer,fastapi developer,software infrastructure,backend platform,internal tools,developer experience,cloud backend,backend devops,desarrollador backend,ingeniero backend',
    7,
    'BACKEND_AUTOMATION',
    10,
    true,
    'Backend con seÃ±ales de operaciÃ³n o automatizaciÃ³n.',
    'BRIDGE',
  ],
  [
    'OBSERVABILITY_NOC',
    'observability engineer,monitoring engineer,monitoring analyst,noc engineer,noc analyst,logging engineer,alerting engineer,ingeniero de monitoreo,analista de monitoreo',
    8,
    'DEVOPS_PLATFORM',
    10,
    true,
    'Especialidad secundaria de observabilidad.',
    'SECONDARY',
  ],
  [
    'IAM_DEVSECOPS',
    'iam analyst,iam engineer junior,identity and access management,access management analyst,devsecops analyst,security automation engineer,security operations engineer,infrastructure security,analista iam,ingeniero iam,seguridad de infraestructura',
    9,
    'DEVOPS_PLATFORM',
    10,
    true,
    'Especialidad secundaria IAM/DevSecOps.',
    'SECONDARY',
  ],
  ['UNRELATED', '', 99, 'CV_TO_CREATE', 999, true, 'Oportunidades no relacionadas.', 'UNRELATED'],
]);

const JOBOPS_STRATEGY_CV_PROFILE_ROWS = Object.freeze([
  [
    'DEVOPS_PLATFORM',
    '',
    'DEVOPS_CLOUDOPS_JR,PLATFORM_SRE_ASSOCIATE,RELEASE_CICD_AUTOMATION,LINUX_INFRASTRUCTURE,OBSERVABILITY_NOC,IAM_DEVSECOPS',
    true,
    'Agregar enlace de Drive.',
  ],
  [
    'CLOUDOPS_SUPPORT',
    '',
    'CLOUD_SUPPORT_OPERATIONS,APPLICATION_PRODUCTION_SUPPORT',
    true,
    'Agregar enlace de Drive.',
  ],
  ['BACKEND_AUTOMATION', '', 'BACKEND_WITH_DEVOPS', true, 'Agregar enlace de Drive.'],
  [
    'CV_TO_CREATE',
    '',
    'UNRELATED',
    true,
    'No existe un CV especÃ­fico o falta configurar su enlace.',
  ],
]);

const JOBOPS_DEFAULT_SOURCE_ROWS = Object.freeze([
  [
    'LinkedIn',
    'linkedin.com',
    'job alert,jobs for you',
    'parseLinkedInJob',
    true,
    0,
    'Fuente inicial.',
  ],
  ['Indeed', 'indeed.com', 'job alert,new jobs', 'parseIndeedJob', true, 0, 'Fuente inicial.'],
  [
    'Get on Board',
    'getonbrd.com',
    'new jobs,job alert',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'WeRemoto',
    'weremoto.com',
    'vacantes,empleos',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'We Work Remotely',
    'weworkremotely.com',
    'remote jobs,job alert',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'ElEmpleo',
    'elempleo.com',
    'ofertas,vacantes',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'Computrabajo',
    'computrabajo.com',
    'ofertas,vacantes',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'Recruiter',
    '',
    'vacancy,position,opportunity,role,vacante,oportunidad,cargo',
    'parseRecruiterJob',
    true,
    0,
    'Detección conservadora; el bono se configura en RECRUITER_SCORE_BONUS.',
  ],
  ['Generic', '', '', 'parseGenericJob', true, 0, 'Fallback para fuentes no reconocidas.'],
]);

const JOBOPS_SHEET_DEFINITIONS = Object.freeze([
  {
    name: JOBOPS_SHEET_NAMES.JOBS,
    headers: JOBOPS_SHEET_HEADERS.Jobs,
    seedRows: Object.freeze([]),
  },
  {
    name: JOBOPS_SHEET_NAMES.SCORING_RULES,
    headers: JOBOPS_SHEET_HEADERS.ScoringRules,
    seedRows: JOBOPS_STRATEGY_SCORING_RULE_ROWS,
    legacySeedRows: JOBOPS_DEFAULT_SCORING_RULE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.ROLE_FAMILIES,
    headers: JOBOPS_SHEET_HEADERS.RoleFamilies,
    seedRows: JOBOPS_STRATEGY_ROLE_FAMILY_ROWS,
    legacySeedRows: JOBOPS_DEFAULT_ROLE_FAMILY_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.CV_PROFILES,
    headers: JOBOPS_SHEET_HEADERS.CVProfiles,
    seedRows: JOBOPS_STRATEGY_CV_PROFILE_ROWS,
    legacySeedRows: JOBOPS_DEFAULT_CV_PROFILE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.SOURCES,
    headers: JOBOPS_SHEET_HEADERS.Sources,
    seedRows: JOBOPS_DEFAULT_SOURCE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.PARSING_ERRORS,
    headers: JOBOPS_SHEET_HEADERS.ParsingErrors,
    seedRows: Object.freeze([]),
  },
  {
    name: JOBOPS_SHEET_NAMES.CONFIG,
    headers: JOBOPS_SHEET_HEADERS.Config,
    seedRows: JOBOPS_DEFAULT_CONFIG_ROWS,
  },
]);

const JOBOPS_REQUIRED_CONFIG_KEYS = Object.freeze(JOBOPS_DEFAULT_CONFIG_ROWS.map((row) => row[0]));

const JOBOPS_HEADER_STYLE = Object.freeze({
  background: '#1F4E78',
  fontColor: '#FFFFFF',
});

const JOBOPS_CONDITIONAL_COLORS = Object.freeze({
  HIGH: '#B7E1CD',
  REVIEW: '#FCE8B2',
  OPTIONAL: '#D2E3FC',
  LOW: '#E8EAED',
  APPLIED: '#D2E3FC',
  REJECTED: '#F4C7C3',
  GHOSTED: '#F4C7C3',
  OFFER: '#B7E1CD',
});

const JOBOPS_ERROR_CODES = Object.freeze({
  CONFIGURATION: 'CONFIGURATION_ERROR',
  SOURCE_NOT_DETECTED: 'SOURCE_NOT_DETECTED',
  PARSER: 'PARSER_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  SHEETS_WRITE: 'SHEETS_WRITE_ERROR',
  GMAIL_LABEL: 'GMAIL_LABEL_ERROR',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  DIGEST: 'DIGEST_ERROR',
  INGESTION_LOCK: 'INGESTION_LOCK_ERROR',
});
