const JOBOPS_SHEET_NAMES = Object.freeze({
  JOBS: 'Jobs',
  SCORING_RULES: 'ScoringRules',
  ROLE_FAMILIES: 'RoleFamilies',
  CV_PROFILES: 'CVProfiles',
  SOURCES: 'Sources',
  PARSING_ERRORS: 'ParsingErrors',
  CONFIG: 'Config',
});

const JOBOPS_SHEET_HEADERS = Object.freeze({
  Jobs: Object.freeze([
    'JOB_ID',
    'DISCOVERED_AT',
    'LAST_UPDATED_AT',
    'SOURCE',
    'ALL_SOURCES',
    'SOURCE_JOB_ID',
    'COMPANY',
    'POSITION',
    'LOCATION',
    'WORK_MODE',
    'JOB_URL',
    'ROLE_FAMILY',
    'MATCH_SCORE',
    'PRIORITY',
    'RECOMMENDED_CV',
    'CV_LINK',
    'SALARY',
    'EXPERIENCE_REQUESTED',
    'REQUIRED_TECHNOLOGIES',
    'STRONG_MATCHES',
    'RISK_FLAGS',
    'RECRUITER_NAME',
    'RECRUITER_EMAIL',
    'GMAIL_MESSAGE_ID',
    'GMAIL_THREAD_ID',
    'DEDUPLICATION_KEY',
    'PARSER',
    'PARSER_VERSION',
    'STATUS',
    'APPLIED_DATE',
    'FOLLOW_UP_DATE',
    'NOTES',
  ]),
  ScoringRules: Object.freeze([
    'RULE_ID',
    'PATTERN',
    'MATCH_TYPE',
    'CONTEXT',
    'SCORE',
    'RISK_FLAG',
    'ENABLED',
    'NOTES',
  ]),
  RoleFamilies: Object.freeze([
    'ROLE_FAMILY',
    'PATTERNS',
    'PRIORITY_ORDER',
    'RECOMMENDED_CV_PROFILE',
    'MINIMUM_REVIEW_SCORE',
    'ENABLED',
    'NOTES',
  ]),
  CVProfiles: Object.freeze([
    'CV_PROFILE',
    'DRIVE_URL',
    'TARGET_ROLE_FAMILIES',
    'ENABLED',
    'NOTES',
  ]),
  Sources: Object.freeze([
    'SOURCE',
    'SENDER_DOMAINS',
    'SUBJECT_PATTERNS',
    'PARSER_NAME',
    'ENABLED',
    'PRIORITY_MODIFIER',
    'NOTES',
  ]),
  ParsingErrors: Object.freeze([
    'TIMESTAMP',
    'GMAIL_MESSAGE_ID',
    'SENDER',
    'SUBJECT',
    'DETECTED_SOURCE',
    'PARSER',
    'ERROR_TYPE',
    'ERROR_MESSAGE',
    'RETRY_COUNT',
    'RESOLVED',
    'NOTES',
  ]),
  Config: Object.freeze(['KEY', 'VALUE', 'DESCRIPTION']),
});

const JOBOPS_APPLICATION_STATUSES = Object.freeze([
  'NEW',
  'REVIEW',
  'READY',
  'APPLIED',
  'FOLLOW_UP',
  'SCREENING',
  'TECHNICAL',
  'REJECTED',
  'GHOSTED',
  'OFFER',
  'SKIPPED',
]);

const JOBOPS_WORK_MODES = Object.freeze(['REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN']);
const JOBOPS_PRIORITIES = Object.freeze(['HIGH', 'REVIEW', 'OPTIONAL', 'LOW']);
const JOBOPS_MATCH_TYPES = Object.freeze(['KEYWORD', 'REGEX', 'PHRASE']);
const JOBOPS_SCORING_CONTEXTS = Object.freeze(['ANY', 'REQUIRED', 'PREFERRED', 'NEGATIVE']);

const JOBOPS_PARSER_VERSION = '1.0.0';
const JOBOPS_TRACKING_QUERY_PARAMETERS = Object.freeze([
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_content',
  'trk',
  'trackingid',
  'ref',
  'source',
]);
const JOBOPS_TECHNOLOGY_NAMES = Object.freeze([
  'Linux',
  'RHEL',
  'CI/CD',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Terraform',
  'Ansible',
  'Prometheus',
  'Grafana',
  'Python',
  'JavaScript',
  'Node.js',
  'GitHub Actions',
  'Jenkins',
  'GitLab CI',
  'IAM',
  'SQL',
]);
const JOBOPS_TECHNICAL_ROLE_SIGNALS = Object.freeze([
  'devops',
  'platform',
  'site reliability',
  'sre',
  'cloud',
  'release',
  'ci/cd',
  'application support',
  'production support',
  'backend',
  'developer',
  'engineer',
  'ingeniero',
  'desarrollador',
  'iam',
  'devsecops',
]);
const JOBOPS_RECRUITER_NEGATIVE_SIGNALS = Object.freeze([
  'newsletter',
  'course',
  'curso',
  'promotion',
  'promoción',
  'invoice',
  'factura',
  'webinar',
  'digest',
  'sale',
  'descuento',
]);

const JOBOPS_GMAIL_LABEL_NAMES = Object.freeze([
  'Jobs/Processed',
  'Jobs/Failed',
  'Jobs/Recruiters',
  'Jobs/Processing',
]);

const JOBOPS_SCRIPT_PROPERTY_KEYS = Object.freeze({
  SPREADSHEET_ID: 'SPREADSHEET_ID',
  USER_EMAIL: 'USER_EMAIL',
});

const JOBOPS_DEFAULT_CONFIG_ROWS = Object.freeze([
  ['TIMEZONE', 'America/Bogota', 'Zona horaria usada por JobOps.'],
  ['DIGEST_ENABLED', true, 'Habilita el resumen diario.'],
  ['DIGEST_HOUR', 8, 'Hora local del resumen diario, entre 0 y 23.'],
  ['FOLLOW_UP_BUSINESS_DAYS', 5, 'Días hábiles antes del seguimiento.'],
  ['MAX_MESSAGES_PER_RUN', 100, 'Máximo de mensajes procesados por ejecución.'],
  ['MAX_DIGEST_JOBS', 10, 'Máximo de vacantes principales en el resumen.'],
  ['HIGH_PRIORITY_THRESHOLD', 15, 'Puntaje mínimo para prioridad HIGH.'],
  ['REVIEW_THRESHOLD', 10, 'Puntaje mínimo para prioridad REVIEW.'],
  ['OPTIONAL_THRESHOLD', 6, 'Puntaje mínimo para prioridad OPTIONAL.'],
  ['RECRUITER_SCORE_BONUS', 5, 'Bono de puntaje para oportunidades de reclutadores.'],
  ['LOOKBACK_DAYS', 7, 'Días de antigüedad incluidos en la búsqueda de Gmail.'],
  ['DRY_RUN', false, 'Procesa sin modificar Gmail, Sheets ni enviar correo.'],
]);

const JOBOPS_DEFAULT_SCORING_RULE_ROWS = Object.freeze([
  ['SCORE_LINUX', 'Linux', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_RHEL', 'RHEL', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_CICD', 'CI/CD', 'PHRASE', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_DOCKER', 'Docker', 'KEYWORD', 'ANY', 4, '', true, 'Regla inicial.'],
  ['SCORE_AWS', 'AWS', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_TERRAFORM', 'Terraform', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_ANSIBLE', 'Ansible', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_PROMETHEUS', 'Prometheus', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  ['SCORE_GRAFANA', 'Grafana', 'KEYWORD', 'ANY', 3, '', true, 'Regla inicial.'],
  [
    'SCORE_PRODUCTION_SUPPORT',
    'Production Support',
    'PHRASE',
    'ANY',
    3,
    '',
    true,
    'Regla inicial.',
  ],
  ['SCORE_PYTHON', 'Python', 'KEYWORD', 'ANY', 2, '', true, 'Regla inicial.'],
  ['SCORE_IAM', 'IAM', 'KEYWORD', 'ANY', 2, '', true, 'Regla inicial.'],
  ['RISK_SENIOR', 'Senior', 'KEYWORD', 'NEGATIVE', -5, 'SENIOR_TITLE', true, 'Riesgo inicial.'],
  ['RISK_LEAD', 'Lead', 'KEYWORD', 'NEGATIVE', -5, 'LEAD_TITLE', true, 'Riesgo inicial.'],
  [
    'RISK_PRINCIPAL',
    'Principal',
    'KEYWORD',
    'NEGATIVE',
    -6,
    'PRINCIPAL_TITLE',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_FIVE_YEARS',
    '5+ years',
    'PHRASE',
    'REQUIRED',
    -4,
    'FIVE_PLUS_YEARS',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_SEVEN_YEARS',
    '7+ years',
    'PHRASE',
    'REQUIRED',
    -6,
    'SEVEN_PLUS_YEARS',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_HELP_DESK_L1',
    'Help Desk L1',
    'PHRASE',
    'ANY',
    -4,
    'HELP_DESK_L1',
    true,
    'Riesgo inicial.',
  ],
  [
    'RISK_SOLE_ON_CALL',
    'sole on-call',
    'PHRASE',
    'REQUIRED',
    -3,
    'SOLE_ON_CALL',
    true,
    'Riesgo inicial.',
  ],
]);

const JOBOPS_DEFAULT_ROLE_FAMILY_ROWS = Object.freeze([
  [
    'DEVOPS_PLATFORM_SRE',
    'devops,platform engineer,site reliability,sre',
    1,
    'DEVOPS_PLATFORM',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'CLOUDOPS_CLOUD_SUPPORT',
    'cloud operations,cloud support,cloud engineer',
    2,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'RELEASE_CICD',
    'release engineer,release management,ci/cd,build engineer',
    3,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'APPLICATION_PRODUCTION_SUPPORT',
    'application support,production support,l2 support,l3 support',
    4,
    'CLOUDOPS_RELEASE_SUPPORT',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'BACKEND_WITH_DEVOPS',
    'backend engineer,backend developer,automation engineer',
    5,
    'BACKEND_AUTOMATION',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'BACKEND_PLATFORM_IAM_DEVSECOPS',
    'iam,devsecops,platform security,backend platform',
    6,
    'BACKEND_AUTOMATION',
    10,
    true,
    'Patrones separados por comas.',
  ],
  [
    'OTHER_TECHNICAL',
    'technical,engineer,developer,operations',
    7,
    'CV_TO_CREATE',
    6,
    true,
    'Familia de respaldo técnico.',
  ],
  ['UNRELATED', '', 8, 'CV_TO_CREATE', 999, true, 'Oportunidades no relacionadas.'],
]);

const JOBOPS_DEFAULT_CV_PROFILE_ROWS = Object.freeze([
  ['DEVOPS_PLATFORM', '', 'DEVOPS_PLATFORM_SRE', true, 'Agregar enlace de Drive.'],
  [
    'CLOUDOPS_RELEASE_SUPPORT',
    '',
    'CLOUDOPS_CLOUD_SUPPORT,RELEASE_CICD,APPLICATION_PRODUCTION_SUPPORT',
    true,
    'Agregar enlace de Drive.',
  ],
  [
    'BACKEND_AUTOMATION',
    '',
    'BACKEND_WITH_DEVOPS,BACKEND_PLATFORM_IAM_DEVSECOPS',
    true,
    'Agregar enlace de Drive.',
  ],
  ['CV_TO_CREATE', '', 'OTHER_TECHNICAL,UNRELATED', true, 'No existe un CV específico.'],
]);

const JOBOPS_DEFAULT_SOURCE_ROWS = Object.freeze([
  [
    'LinkedIn',
    'linkedin.com',
    'job alert,jobs for you',
    'parseLinkedInJob',
    true,
    0,
    'Fuente inicial.',
  ],
  ['Indeed', 'indeed.com', 'job alert,new jobs', 'parseIndeedJob', true, 0, 'Fuente inicial.'],
  [
    'Get on Board',
    'getonbrd.com',
    'new jobs,job alert',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'WeRemoto',
    'weremoto.com',
    'vacantes,empleos',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'We Work Remotely',
    'weworkremotely.com',
    'remote jobs,job alert',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'ElEmpleo',
    'elempleo.com',
    'ofertas,vacantes',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'Computrabajo',
    'computrabajo.com',
    'ofertas,vacantes',
    'parseGenericJob',
    true,
    0,
    'Parser genérico inicial.',
  ],
  [
    'Recruiter',
    '',
    'vacancy,position,opportunity,role,vacante,oportunidad,cargo',
    'parseRecruiterJob',
    true,
    0,
    'Detección conservadora; el bono se configura en RECRUITER_SCORE_BONUS.',
  ],
  ['Generic', '', '', 'parseGenericJob', true, 0, 'Fallback para fuentes no reconocidas.'],
]);

const JOBOPS_SHEET_DEFINITIONS = Object.freeze([
  {
    name: JOBOPS_SHEET_NAMES.JOBS,
    headers: JOBOPS_SHEET_HEADERS.Jobs,
    seedRows: Object.freeze([]),
  },
  {
    name: JOBOPS_SHEET_NAMES.SCORING_RULES,
    headers: JOBOPS_SHEET_HEADERS.ScoringRules,
    seedRows: JOBOPS_DEFAULT_SCORING_RULE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.ROLE_FAMILIES,
    headers: JOBOPS_SHEET_HEADERS.RoleFamilies,
    seedRows: JOBOPS_DEFAULT_ROLE_FAMILY_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.CV_PROFILES,
    headers: JOBOPS_SHEET_HEADERS.CVProfiles,
    seedRows: JOBOPS_DEFAULT_CV_PROFILE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.SOURCES,
    headers: JOBOPS_SHEET_HEADERS.Sources,
    seedRows: JOBOPS_DEFAULT_SOURCE_ROWS,
  },
  {
    name: JOBOPS_SHEET_NAMES.PARSING_ERRORS,
    headers: JOBOPS_SHEET_HEADERS.ParsingErrors,
    seedRows: Object.freeze([]),
  },
  {
    name: JOBOPS_SHEET_NAMES.CONFIG,
    headers: JOBOPS_SHEET_HEADERS.Config,
    seedRows: JOBOPS_DEFAULT_CONFIG_ROWS,
  },
]);

const JOBOPS_REQUIRED_CONFIG_KEYS = Object.freeze(JOBOPS_DEFAULT_CONFIG_ROWS.map((row) => row[0]));

const JOBOPS_HEADER_STYLE = Object.freeze({
  background: '#1F4E78',
  fontColor: '#FFFFFF',
});

const JOBOPS_CONDITIONAL_COLORS = Object.freeze({
  HIGH: '#B7E1CD',
  REVIEW: '#FCE8B2',
  OPTIONAL: '#D2E3FC',
  LOW: '#E8EAED',
  APPLIED: '#D2E3FC',
  REJECTED: '#F4C7C3',
  GHOSTED: '#F4C7C3',
  OFFER: '#B7E1CD',
});

const JOBOPS_ERROR_CODES = Object.freeze({
  CONFIGURATION: 'CONFIGURATION_ERROR',
  SOURCE_NOT_DETECTED: 'SOURCE_NOT_DETECTED',
  PARSER: 'PARSER_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  SHEETS_WRITE: 'SHEETS_WRITE_ERROR',
  GMAIL_LABEL: 'GMAIL_LABEL_ERROR',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  INGESTION_LOCK: 'INGESTION_LOCK_ERROR',
});
